name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / <linter-name> (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          locale: "US"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          locale: "US"
          workdir: ./testdata

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          reviewdog_flags: -filter-mode=file -fail-on-error
